config/routes.rb
PropertyManagement::Application.routes.draw do
  resources :buildings
  resources :owners

  root 'buildings#index'

end

app/models/building.rb
class Building < ActiveRecord::Base
  STATES = %w{Alabama Alaska Arizona Arkansas California Colorado Connecticut Delaware DC Florida Georgia Hawaii Idaho Illinois Indiana Iowa Kansas Kentucky Louisiana Maine Maryland Massachusetts Michigan Minnesota Mississippi Missouri Montana Nebraska Nevada New Hampshire New Jersey New Mexico New York North Carolina North Dakota Ohio Oklahoma Oregon Pennsylvania Puerto Rico Rhode Island South Carolina South Dakota Tennessee Texas Utah Vermont Virginia Washington West Virginia Wisconsin Wyoming}

  validates_presence_of :address
  validates_presence_of :city
  validates_inclusion_of :state, in: STATES
  validates_presence_of :zip, numericality: true

  belongs_to :owner,
    inverse_of: :buildings,
    dependent: :destroy


end

app/models/owner.rb
class Owner < ActiveRecord::Base
  validates_presence_of :last_name
  validates_presence_of :first_name
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }, presence: true

  has_many :buildings,
    inverse_of: :owner

  def owner_full_name
    "#{last_name}, #{first_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  def index
    @buildings = Building.all
    @owners = Owner.all
  end

  def new
    @building = Building.new
    @owners = Owner.all
  end

  def create
    @building = Building.new(building_params)
    @owners = Owner.all

    if @building.save
      redirect_to @building, notice: "Building was saved successfully."
    else
      render action: 'new'
    end
  end

  def show
    @building = Building.find(params[:id])
  end

  def edit
    @building = Building.find(params[:id])
  end

  def update
    @building = Building.find(params[:id])
    if @building.update(building_params)
      redirect_to @building, notice: "Building was updated successfully"
    else
      render action: 'edit'
    end
  end

  def destroy
    @building = Building.find(params[:id])
    if @building.destroy
      redirect_to buildings_url, notice: "Building was successfully deleted"
    end
  end

  private
    def building_params
      params.require(:building).permit(:address, :city, :state, :zip, :description, :owner_id)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.all
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      redirect_to @owner, notice: "Owner was saved successfully."
    else
      render action: 'new'
    end
  end

  def show
    @owner = Owner.find(params[:id])
  end

  def edit
    @owner = Owner.find(params[:id])
  end

  def update
    @owner = Owner.find(params[:id])
    if @owner.update(owner_params)
      redirect_to @owner, notice: "Owner was updated successfully"
    else
      render action: 'edit'
    end
  end


  def destroy
    @owner = Owner.find(params[:id])
    if @owner.destroy
      redirect_to owners_url, notice: "Owner was successfully deleted"
    end
  end


  private
    def owner_params
      params.require(:owner).permit(:first_name, :last_name, :email, :company)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buildings/_form.html.erb
<%= form_for(@building) do |f| %>
<% if @building.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@building.errors.count, "error") %> occured: </h2>

    <ul>
    <% @building.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :address %><br>
  <%= f.text_field :address %>
  <br>
  <%= f.label :city %><br>
  <%= f.text_field :city %><br>
  <br>
  <%= f.label :state %><br>
  <%= f.select :state, collection:  Building::STATES %><br>
  <br>
  <%= f.label :zip %><br>
  <%= f.text_field :zip %><br>
  <br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>

  <%= f.label :owner %><br/>
  <%= collection_select( :building, :owner_id, Owner.all, :id, :owner_full_name , {include_blank: 'None'}) %><br/>
  <br>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/buildings/_form.html.erb.html.erb
<%= form_for(@building) do |f| %>
<% if @building.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@building.errors.count, "error") %> occured: </h2>

    <ul>
    <% @building.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :address %><br>
  <%= f.text_field :address %>
  <br>
  <%= f.label :city %><br>
  <%= f.text_field :city %><br>
  <br>
  <%= f.label :state %><br>
  <%= f.select :state, collection:  Building::STATES %><br>
  <br>
  <%= f.label :zip %><br>
  <%= f.text_field :zip %><br>
  <br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <br>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Edit Building</h1>
<%= render 'form' %>

app/views/buildings/index.html.erb
<h1>Property Management</h1>
<%= link_to "Add Building", new_building_path %> |
<%= link_to "Add Owner", new_owner_path %> |
<%= link_to "Go to Owners", owners_path %>


<table cellpadding=5, cellspacing=0, border=0>
  <thead>
    <td>Address</td>
    <td>City</td>
    <td>State</td>
    <td>Zip code</td>
    <td>Description</td>
    <td>Owner</td>
    <td>Actions</td>
  </thead>
  <% @buildings.each do |building| %>
    <tr>
      <td><%= building.address %></td>
      <td><%= building.city %></td>
      <td><%= building.state %></td>
      <td><%= building.zip %></td>
      <td><%= building.description %></td>
      <% if building.owner != nil %>
        <td><%= building.owner.first_name %> <%= building.owner.last_name %></td>
      <% else %>
        <td>None</td>
      <% end %>
      <td>
        <%= link_to 'Show', building_path(building) %> |
        <%= link_to 'Edit', edit_building_path(building) %> |
        <%= link_to 'Delete', building, method: :delete %>
      </td>
    </tr>
  <% end %>
</table>

app/views/buildings/new.html.erb
<h1>Add New Building</h1>
<%= render 'form' %>

app/views/buildings/show.html.erb
<table cellpadding=0, cellspacing=0, border=0>
  <tr>
    <td>Address:</td>
    <td><%= @building.address %></td>
  </tr>
  <tr>
    <td>City:</td>
    <td><%= @building.city %></td>
  </tr>
  <tr>
    <td>State:</td>
    <td><%= @building.state %></td>
  </tr>
  <tr>
    <td>Zip Code:</td>
    <td><%= @building.zip %></td>
  </tr>
  <tr>
    <td>Description:</td>
    <td><%= @building.description %></td>
  </tr>
  <tr>
    <td>Owner:</td>
    <% if @building.owner != nil %>
      <td><%= @building.owner.first_name %> <%= @building.owner.last_name %></td>
    <% else %>
      <td>None</td>
    <% end %>
  </tr>

</table>

<%= link_to "Back to Property Management", root_path %>
<%= link_to "Edit", edit_building_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PropertyManagement</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %>
<p class="alert"><%= alert %>
<%= yield %>

</body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
<% if @owner.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@owner.errors.count, "error") %> occured: </h2>

    <ul>
    <% @owner.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %>
  <br>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>
  <br>
  <br>
  <%= f.label :email %><br>
  <%= f.text_field :email %><br>
  <br>
  <%= f.label :company %><br>
  <%= f.text_area :company %><br>
  <br>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/owners/edit.html.erb
<h1>Edit Owner</h1>
<%= render 'form' %>

app/views/owners/index.html.erb
<h1>Owners Listing</h1>
<%= link_to "Add Building", new_building_path %> |
<%= link_to "Add Owner", new_owner_path %> |
<%= link_to "Go to Property Management", root_path %>


<table cellpadding=5, cellspacing=0, border=0>
  <thead>
    <td>Last Name</td>
    <td>First Name</td>
    <td>Email</td>
    <td>Company</td>
    <td>Actions</td>
  </thead>
  <% @owners.each do |owner| %>
    <tr>
      <td><%= owner.last_name %></td>
      <td><%= owner.first_name %></td>
      <td><%= owner.email %></td>
      <td><%= owner.company %></td>
      <td>
        <%= link_to 'Show', owner_path(owner) %> |
        <%= link_to 'Edit', edit_owner_path(owner) %> |
        <%= link_to 'Delete', owner, method: :delete %>
      </td>

    </tr>
  <% end %>
</table>

app/views/owners/new.html.erb
<h1>Add Owner</h1>
<%= render 'form' %>

app/views/owners/show.html.erb
Last Name: <%= @owner.last_name %><br/>
First Name: <%= @owner.first_name %><br/>
Email: <%= @owner.email %><br/>
Company: <%= @owner.company %><br/><br/>

<%= link_to "Back to Property Management", root_path %>
<%= link_to "Edit", edit_owner_path %>